import Config

# Configure your database
# Port 15443 allocated per ~/PORT_ALLOCATION.md for Personal GitHub projects
config :conezia, Conezia.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: 15443,
  database: "conezia_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :conezia, ConeziaWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # Port 14013 allocated per ~/PORT_ALLOCATION.md for Personal GitHub projects
  http: [ip: {127, 0, 0, 1}, port: 14013],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "gNOKQTdXPKXaLI+Nv5UUbfK0J6uYTuJXg+U8wqJyLNOZEGUSkeSjTBvjQNtgyq56",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:conezia, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:conezia, ~w(--watch)]}
  ]

# Watch static and templates for browser reloading.
config :conezia, ConeziaWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/conezia_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :conezia, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Google OAuth configuration (from environment variables)
config :conezia, :google_oauth,
  client_id: System.get_env("GOOGLE_CLIENT_ID"),
  client_secret: System.get_env("GOOGLE_CLIENT_SECRET")

# LinkedIn OAuth configuration (optional, from environment variables)
# If not set, LinkedIn will show as "Coming Soon" in Settings
if System.get_env("LINKEDIN_CLIENT_ID") do
  config :conezia, :linkedin_oauth,
    client_id: System.get_env("LINKEDIN_CLIENT_ID"),
    client_secret: System.get_env("LINKEDIN_CLIENT_SECRET")
end

# Facebook OAuth configuration (optional, from environment variables)
# If not set, Facebook will show as "Coming Soon" in Settings
# Get credentials from https://developers.facebook.com/apps
if System.get_env("FACEBOOK_CLIENT_ID") do
  config :conezia, :facebook_oauth,
    client_id: System.get_env("FACEBOOK_CLIENT_ID"),
    client_secret: System.get_env("FACEBOOK_CLIENT_SECRET")
end
